sonar.projectKey=ffreis-platform-orchestrator
sonar.organization=felipefuhr
sonar.sources=.
sonar.exclusions=vendor/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.issue.ignore.block=e1
sonar.issue.ignore.block.e1.beginBlockRegexp=//BEGIN-SONAR-IGNORE-OIDC-THUMBPRINT
sonar.issue.ignore.block.e1.endBlockRegexp=//END-SONAR-IGNORE-OIDC-THUMBPRINT